// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwBuhw1NU-4ITWOrz2wWTtwH0_lXvzegM',
    appId: '1:971905033685:web:c579a0372681cf3294895c',
    messagingSenderId: '971905033685',
    projectId: 'tutorial-ee980',
    authDomain: 'tutorial-ee980.firebaseapp.com',
    storageBucket: 'tutorial-ee980.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ_GGVqj96iQKUmrS9d9K9xkI5dPXOUKw',
    appId: '1:971905033685:android:45273d520e9b2a9794895c',
    messagingSenderId: '971905033685',
    projectId: 'tutorial-ee980',
    storageBucket: 'tutorial-ee980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_5dELzsuCEn-frxLZyROCSxBad6HVskQ',
    appId: '1:971905033685:ios:91828eca4c50310b94895c',
    messagingSenderId: '971905033685',
    projectId: 'tutorial-ee980',
    storageBucket: 'tutorial-ee980.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_5dELzsuCEn-frxLZyROCSxBad6HVskQ',
    appId: '1:971905033685:ios:91828eca4c50310b94895c',
    messagingSenderId: '971905033685',
    projectId: 'tutorial-ee980',
    storageBucket: 'tutorial-ee980.firebasestorage.app',
    iosBundleId: 'com.example.taskmanager2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwBuhw1NU-4ITWOrz2wWTtwH0_lXvzegM',
    appId: '1:971905033685:web:69a557179491506394895c',
    messagingSenderId: '971905033685',
    projectId: 'tutorial-ee980',
    authDomain: 'tutorial-ee980.firebaseapp.com',
    storageBucket: 'tutorial-ee980.firebasestorage.app',
  );
}
